### PR TITLE
Fixed issues from changes to non-English load actions in CP 2.1.0+

### PR DESCRIPTION
**Pull request by silicon-git**
I also changed the manifest version to 2.0.3-unofficial. Hope I'm doing all this github stuff right

### CODE REVIEW

**Review by silicon-git — COMMENTED** [review]
okay I didn't mean to include this commit... sorry, I'm clearly a bit too new to this. might try and set up my git bash terminal so I can figure out how to delete this

**Comment by mus-candidus** [comment]
Hi, thanks for your PR! Can you describe briefly what issue you had and how I can reproduce it? I read the CP documentation but didn't quite understand what changed :-)

**Comment by silicon-git** [comment]
So when using any language other than English, LittleNPCs content packs will fail to load assets properly in Content Patcher 2.1.0 and later due to a change made in Content Patcher 2.1.0 to the way Load actions work in non-English languages. 
Basically, LittleNPCs will load its fallback assets to an asset suffixed with the language code of the current game language (as it's always done), but Content Patcher will no longer target that language code for load actions and any CP assets will fail to load.

**Comment by mus-candidus** [comment]
Thanks again! Sorry that it took so long.

**Pull request merged**
